## Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import numbers
s = 0
n = 4000000
a,b,c = 1, 1, 2
while b <= n:
    print(b)
    if b % 2 == 0:
        s = s+b
    # calculate the next fibonacci numbers
    a, b = b, a + b
    # c = a
    # a = b
    # b = c+b 
print('euler 2: ', s)
